### ISSUE TITLE
404 Not Found: / after setup

### ISSUE THREAD

**Issue by spidgorny** [jhuckaby/performa#14]
While the server is running the website only replies with

> 404 Not Found: /

Looks like routes are not setup properly. I've used the default config file.

Any ideas?

**Comment by spidgorny** [comment]
renamed /index-dev.html to /index.html - looks better now. But I'm missing /js/common folder.

**Comment by jhuckaby** [comment]
Uhh....

You have a very messed up installation.  It looks like the installer script never even ran.

I have no idea how you even got to this point (did you try to install it manually from source or something?), but you need to run this at the very least:

```
cd /opt/performa
node bin/build.js dist
```

Please refer to the install instructions, as I feel like something is very wrong with your installation: https://github.com/jhuckaby/performa#installation

--
Joseph Huckaby
***@***.***

**Comment by spidgorny** [comment]
> node bin/build.js dist

helps. Need to RTFM more carefully.
Thanks.
