### ISSUE TITLE
Can performa support GPU / multi- hard drives monitoring ？

### ISSUE THREAD

**Issue by xiachenrui** [jhuckaby/performa#18]
Thanks for developping this amazing tool! I really love and enjoy using it!

I would like to know if  performa  can support GPU monitoring or  monitoring multiple hard drives

Thanks！

**Comment by jhuckaby** [comment]
Thanks!

You can monitor "anything" as long as there is a command-line executable that outputs information that you can scrape.

First, add a "Command" that runs your command-line executable: https://github.com/jhuckaby/performa#commands

Commands are executed on every server they target every minute.

Then you can scrape bits of information from the output of the command, either using JSON paths (if the command outputs JSON) or a regular expression if the command outputs text, and pull that information (typically a number) into a "Monitor".

https://github.com/jhuckaby/performa#data-sources

Good luck!
