### ISSUE TITLE
Add user to view select groups

### ISSUE THREAD

**Issue by micron10** [jhuckaby/performa#20]
Hi @jhuckaby 

Is there options to set group per user

like 

username : peter to see only group1, group2, group3
username : jhon to see group4,group5, group6

m

**Comment by jhuckaby** [comment]
Hi there!  Well, peter should definitely not have access to group1.  He forfeited that privilege after "the incident" 😝 

Jokes aside, I am implementing this functionality into my upcoming "Orchestra" product, which is the spiritual successor to Performa.

It should be released later this year (2023).  However, if I miss that deadline, I'll backport the feature to Performa 😊

**Comment by micron10** [comment]
is there any options to contact with you?

**Comment by jhuckaby** [comment]
I'm not sure what you mean.  Are we not communicating right now?

**Comment by micron10** [comment]
telegram or whatsapp 
i what to talk with you for extended module.
and to pay for this

**Comment by jhuckaby** [comment]
I apologize, but I'm very busy, and just don't have the time to add extended modules.  But the feature you are asking for will be in Performa v2 (Orchestra).

Thank you for your interest in the product!

**Comment by micron10** [comment]
I like Performa work very good
Thank you I'll keep an eye out for changes.

And will wait Orchestra
