### ISSUE TITLE
Question: Stacking metrics and current server info's data enrichment

### ISSUE THREAD

**Issue by liketoeatcheese** [jhuckaby/performa#23]
Hey mate,

Awesome tool! 

Few questions:
1. Is there any way to stack multiple different commands together with different colours? For example, I want to add used_mem on top of total_mem to see what my limits are. 
2. The Current Server Info's Disk pie chart only shows the root mount, is there a way to add for other drives as well?

**Comment by jhuckaby** [comment]
Hi there!

For (1) I'm so sorry, but there is currently no way to stack monitors on top of each other in the same graph.  I'll add this as a feature request for the next major version.

For (2) yes, you can customize the disk monitoring system to look at other mounts.  The way to do this is to add a new monitor that looks at a different mount in the metrics data.

For example if you look at the current Disk Usage monitor, you'll see:

![](https://pixlcore.com/screenshots/Screenshot_2024-06-26_at_12.18.40_PM.png)

You can add a new monitor that looks at a different mount.  Click the "Explore" button to see which data is available to you:

![](https://pixlcore.com/screenshots/Screenshot_2024-06-26_at_12.20.33_PM.png)

If you have any other disk mounts, they should be shown here, and you can create a monitor that points to one.  

For e.g. on one of my servers I have a "data" mount that I monitor separately:

![](https://pixlcore.com/screenshots/Screenshot_2024-06-26_at_12.21.09_PM.png)

Good luck!

**Comment by liketoeatcheese** [comment]
Thanks for that :)
