### ISSUE TITLE
Database Size?

### ISSUE THREAD

**Issue by Ruok2bu** [jhuckaby/performa#29]
How big can the database get for 1 machine after 1 year? I ask because i need to reinstall my server and partition the hard drive but i want to plan ahead for when im monitoring dozens of machines.

**Comment by jhuckaby** [comment]
Approximately 360MB per server per year.  That can vary based on a lot of things (how many alerts, how many snapshots, custom monitors), but that's an average.

Also note that if you choose to host on a local filesystem, make sure you have lots of INODEs allocated.  At least 100,000 per server per year.

**Comment by Ruok2bu** [comment]
Thanks for fast reply!
