### ISSUE TITLE
Nothing Logged

### ISSUE THREAD

**Issue by Ruok2bu** [jhuckaby/performa#30]
I installed Performa and the Performa Satellite on the same machine. Both are using the same secret but nothing is being logged on the web panel. Even 2 days later.

I ran ./bin/control.sh debug to see whats happening and i can see in the logs the following:

`[1727189525.21][2024-09-24 10:52:05][xxxxxx][104227][WebServer][transaction][HTTP 200 OK][/api/app/hello][{"id":"r29","method":"POST","proto":"https","ip":"x.x.x.x","ips":["x.x.x.x"],"port":xxxx,"socket":"cs28","perf":{"scale":1000,"perf":{"total":38.651,"queue":0.034,"read":0.488,"process":0.655,"encode":0.323,"write":0.728},"counters":{"bytes_in":267,"bytes_out":223,"num_requests":1}},"host":"x.x.x.x:xxxx","ua":"Performa-Satellite/1.1.4"}]

In performa satellite, when i manually run satellite i get this error:
`Warning: Performa Satellite Error: API returned: Missing parameter: nonce`
`
Why arent any stats being displayed?

**Comment by jhuckaby** [comment]
I can't tell what is going on from the single log row you included.  Try setting your `debug_level` to 9 or 10 and try again?

Make sure both Performa and Performa Satellite are on the latest versions.  There was a recent security vulnerability discovered, and I had to redesign the protocol by which the two communicate with each other.

Good luck.

**Comment by Ruok2bu** [comment]
Aha! That fixed it. The installation command on github links to version 1.0.0.  I ran the upgrade script afterwards to fix it.
