### ISSUE TITLE
How to delete server?

### ISSUE THREAD

**Issue by asyslinux** [jhuckaby/performa#4]
Hello.

I didn`t find how to delete server from monitoring.
Have a method for delete?

Thanks.

**Comment by jhuckaby** [comment]
It happens automatically.  Eventually the server will disappear from graphs and the menus, as soon as the data becomes stale.  This process is different for menus and graphs:

The drop-down menus like "Jump to Server" contain the last 24 hours worth of servers.  Graphs only show data from servers actively submitting data.  Once the data scrolls off the graph, the old server's line and color will disappear.
